[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  [context.production.environment]
    VITE_API_URL = "http://api.sipanda.online"

[context.branch-deploy]
  [context.branch-deploy.environment]
    VITE_API_URL = "http://api-dev.sipanda.online"

[context.deploy-preview]
  [context.deploy-preview.environment]
    VITE_API_URL = "http://api-dev.sipanda.online"
