[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  [context.production.environment]
    VITE_API_URL = "https://api.sipanda.online"

[context.branch-deploy]
  [context.branch-deploy.environment]
    VITE_API_URL = "https://api.sipanda.online"

[context.deploy-preview]
  [context.deploy-preview.environment]
    VITE_API_URL = "https://api.sipanda.online"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
